### ISSUE TITLE
Question towards wiring diagram

### ISSUE THREAD

**Issue by nenadmilano** [RealByron/PicoW-Intex-PureSpa#6]
Hello Byron,

first up thanks for your project, I am so looking forward to being able to remotely control my „dumb“ spa!!

Currently I am stuck in the soldering phase and cannot get the Pico to power up. Maybe I am reading your wiring diagram wrong so hence I am asking for help.

My understanding is that LV goes towards the 3V3 pin and the condensator goes from VSYS to GND.
I see in your photo that there seems to be a connection between GND from the level shifter to VSYS which is not in the diagram - can you elaborate on that?
![IMG_0531](https://github.com/RealByron/PicoW-Intex-PureSpa/assets/32328649/b7dbda94-efd9-4fdd-b980-bac3d454e096)

My understanding is that the VSYS should be used to input betwen 3-5V to the Pico but with this constellation I would not understand how it should get the down shifter voltage from the level shifter board.

Thank you very much for your help!
best regards from Vienna,
Nenad

**Comment by jonpeltier11** [comment]
Nenad, I got this project to work and it is a marvel of simplicity! I preface everything I am about to write with a disclaimer that I am not an electronic specialist. I just try really hard! I am very grateful to RealByron! Some of the wires you see in the en situ photos are not in the diagram. I was confused by this. Furthermore, the en situ photo looks like VSYS is soldered  to ground. It is not. I think that is a broken wire. VSYS should be hooked up to 5 volts, before the level shifter.  What I have found is that the board is being powered up with 5 volts, not 3.3. this makes sense because you have Wi-Fi that you need to power and stuff like that. You're tapping 5 volts from the spa main board into the pico. You also need to ground the pico with the main board, before the level shifter.   Once I did those two things, the board came to life and it just plum worked, like a champ!

**Comment by nenadmilano** [comment]
Hey @jonpeltier11, thanks for your quick reply!
So if I understand your correctly then I have to directly connect VSYS to +5 from the Spa and GND also directly from the Spa connector? What about the condensator between VSYS and GND, is this needed in the end? What do I solder to the 3V3 port then?

**Comment by jonpeltier11** [comment]
Yes, 5 volts from the spa, achieved by soldering before the level shifter. So that red wire that you see in the photo is actually soldered to the five volt pin, the HV pin.  It only looks like it's soldered to ground but I think what happened is the wire broke off of the HV pin and kind of laid up against the ground pin. The blue wire, on the left, goes from spa ground to pico ground. And yes, I would include the capacitor. It's there for a reason, I can't tell you why because I am just a clown, lol. What's happening is the board is accepting 5 volts, and then providing 3.3 volts to the level shifter through the LV pin, just like in the wiring diagram. This is done so the level shifter can have a  3.3 volt reference voltage. It will not work without it. All of this really confused me. Because I had read somewhere that some people actually power their Pico through the 3.3_OUT pin! And my stupid self thought that's what was going on here, lol! After you get all of this hooked up, you have to compile it through home assistant, specifically in ESPhome developer version. Your going to have to use the developer version of ESPhome because that is the only version, that I know of, that compiles for the pico. That's a whole other fight that I had with this project. But it's so worth it, this project saves me immense time and effort and expense.

**Comment by nenadmilano** [comment]
Nice, thanks @jonpeltier11, the pico is powered now!!

Now I just have to work on getting the sensor and climate entities to appear in Home Assistant. For now I just see the Firmware sensor from ESPHome but nothing else. Is my Config correct or do I need to do anything else?

![IMG_0532](https://github.com/RealByron/PicoW-Intex-PureSpa/assets/32328649/bc3c46ba-e2f3-4e8c-846a-eeeadc6980ef)

![IMG_0533](https://github.com/RealByron/PicoW-Intex-PureSpa/assets/32328649/ad7f902c-6d29-4b53-b7bd-80036a3edde9)

**Comment by jonpeltier11** [comment]
I am certainly no expert on this but I did get it to work... Once you get the correct firmware uploaded to the Pico, via USB cable, everything should fall into place as long as your router plays nice. You should only have to add it to your dashboard. I will pass this on to you, I added three lines of code to my spa yaml so that I could keep an eye on the temperature of the pico interface. See one of the screenshots attached. You may not find it necessary, mine never seems to go over 43° c / 110° f and I live in a very hot and humid climate.  Right now, my spy water is at 40° c / 104° f and it is 35° c / 94° f outside. All of this in my Pico temperature is at 42° c/107° f.  Did you upload the firmware to the Pico with a USB cable, using ESP home developer version? If you have, check to see if it shows online and then go to the logs and see if it is communicating. Log should show something like the screenshot I am attaching.

![Screenshot_20240623_153939_Chrome Beta](https://github.com/RealByron/PicoW-Intex-PureSpa/assets/82741127/572bfac5-5972-41bf-80b3-d27724c10685)


![Screenshot_20240623_151732_Chrome Beta](https://github.com/RealByron/PicoW-Intex-PureSpa/assets/82741127/70f35a73-afc3-4a72-9f03-6b999d4aefe0)

**Comment by nenadmilano** [comment]
Thanks a bunch @jonpeltier11, now it works!! I had to include the part after purespa: which I commented out for whatever reason and now all sensors show up and I can control it from Home Assistant!!!

**Comment by nenadmilano** [comment]
Closed but would recommend to update the readme to make the soldering layout and YAML content more precise.
